### ISSUE TITLE
Familiarization with version control

### ISSUE THREAD

**Issue by Muslinmin** [Muslinmin/glowing-waffle#1]
**GitHub Basics**

GitHub is where all our project files are stored and is what we use for version control.

- [x] Learn how to assign issues by assigning yourself to this issue using the Assignees row in the column on the right of this comment
- [x] Learn how to organize issues by adding a "version_chores" label to this issue using the Labels row in the column on the right of this comment
- [x] Explore the Issues tab to understand how you may browse and view issues
- [x] Explore the Wiki tab to understand how we can use GitHub's Wiki to document things

**GitHub for Source Control & Development**

 GitHub is also used as a project management stand-in app, where we post our issues (tracks), deadlines, etc.

- [x] Create your own dev-branch e.g. dev-reuben and reference from the main branch
- [x] Push some random updates to your own branch
- [x] Showcase your repository by commenting here with a link, https://github.com/LordMuze/cli, using the edit mode on the top right of this issue. 
- [ ] (Optional) Understand how to use GitHub Desktop

- [ ] Add this issue to the Kanban board under the Projects tab --> Projects --> Embedded Systems Project
- [x] Continue adding a Status, Priority, Effort and Deadline to this issue using the rows on the right of this page
- [ ] Explore how the Kanban board works by navigating it to from the top menu, Projects --> Projects --> Immersification Kanban
- [x] #3

- [x] 'to be converted'
- [x] 'to be converted'

**Comment by Muslinmin** [comment]
So are you still keen on using this tool? @s2200931

**Comment by s2200931** [comment]
> So are you still keen on using this tool? @s2200931

Yes, your grace.
